In [8]:
def person(fname):
    print(fname+"trump")
    

In [9]:
# function call
person("donald")

donaldtrump


In [5]:
def person(fname):
    print(fname + " trump ")

In [6]:
person("donald")

donald trump 


In [ ]:
# syntax with return statment


In [10]:
def add(a,b):
    return a+b


In [12]:
add(2,3)

5

In [13]:
add(2,5)

7

In [14]:
# function can return multiple values
def mul(a,b):
    return a*b

In [15]:
mul(5,2)

10

In [16]:
mul(4,6)

24

In [17]:
mul(78,893)

69654

In [18]:
# function can return division values
def div(a,b):
    return a/b


In [20]:
div(14,7)

2.0

In [21]:
div(50,10)

5.0

In [22]:
div(78,2)

39.0

In [23]:
def add(a,b):
    return a+b,a

In [24]:
add(2,5)

(7, 2)

In [25]:
def swap(a,b):
    a,b=b,a
    print(a)
    print(b)

In [26]:
swap(4,5)

5
4


In [27]:
def swap(a,b):
    temp=a
    a=b
    b=temp
    print(a)
    print(b)

In [28]:
swap(2,4)

4
2


## NUMPY

In [1]:
!pip install numpy
import numpy as np

In [65]:
#1-d array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [14]:
type(arr1)

numpy.ndarray

In [15]:
print(arr1.ndim)

1


In [66]:
# 2-d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [20]:
type(arr2)

numpy.ndarray

In [21]:
print(arr2.ndim)

2


In [67]:
arr3=np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [68]:
arr3=np.ones((5,5))
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
print(arr3.ndim)

2


In [69]:
arr3=np.ones((6,8))
print(arr3)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
print(arr3.ndim)

2


In [70]:
arr3=np.ones((5,5))
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
print(arr3.ndim)

2


In [71]:
arr5=np.ones((5,9))
print(arr5)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
print(arr5.ndim)

2


In [72]:
# 0-d Array
arr3=np.array([1,2,3,4,5])
print(arr3)

[1 2 3 4 5]


In [76]:
arr3=np.array([1,2,3,4,5])
print(arr3[0])

1


In [75]:
arr3=np.array([101])
print(arr3)

[101]


In [24]:
## accessing array elements

In [11]:
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [37]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(arr1[4])

[ 9 10]


In [38]:
# 2nd elements on list 1st row

In [43]:
print(arr1[1])

[3 4]


In [ ]:
import numpy as np

In [44]:
arr3=np.array([1,2,3,4,5,6,7,8,9])
print(arr3[1:5])

[2 3 4 5]


In [48]:
print(arr3[1:7])

[2 3 4 5 6 7]


In [50]:
print(arr3[:7])

[1 2 3 4 5 6 7]


In [51]:
print(arr3[:10])

[1 2 3 4 5 6 7 8 9]


In [52]:
print(arr3[-9:])

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr3[-3:-1])

In [81]:
print(arr3[-3:-1])

[7 8]


In [59]:
arr7=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr7[2:5:2])

[3 5]


In [61]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [67]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [68]:
## Reshape from 1-d and 3-d
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [74]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [75]:
# iterating arrays
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [78]:
# iterate on the eiement of the following 2-d
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [79]:
arr=([[11,21,31,41,51],[12,22,32,42,52],[13,23,34,43,53]])
for x in arr:
    print(x)


[11, 21, 31, 41, 51]
[12, 22, 32, 42, 52]
[13, 23, 34, 43, 53]


In [64]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2))
print(arr)

In [84]:
# splitting two 2-d  numpy array
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [18]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,5)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [20]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [21]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,7)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [44]:
# random numbers.
# numpy offers the random module to work with random number.
# generate aa random integer from 0 to 100:
from numpy import random
x=random.randint(100)
print(x)

24


In [79]:
# random module's rand() method returns a random float between 0 to 1.
from numpy import random 
x=random.rand(1)
print(x)

[0.36783952]


In [87]:
# generate random array
from numpy import random 
x=random.randint(100,size=(5))
print(x)

[ 6 21 45 53 57]


In [89]:
from numpy import random 
x=random.randint(100,size=(5,3,4))
print(x)

[[[36 73 72 65]
  [48 12  5 72]
  [50 12 48 71]]

 [[ 4 85 22 77]
  [94 11 94 16]
  [92 66 49 81]]

 [[63 58 45 93]
  [99 10 87 45]
  [37 11 38 49]]

 [[64 65 33 88]
  [ 1  6 53 50]
  [85 37 44 33]]

 [[68 35 86 75]
  [78 54 25  8]
  [26 86  1 60]]]


In [90]:
from numpy import random 
x=random.randint(100,size=(5,3))
print(x)

[[70 51 60]
 [76 61 60]
 [60 43 92]
 [33  9 49]
 [59  5 55]]


In [1]:
# generate a 1-D array containing 5 random float.
from numpy import random 
x=random.rand(5,3)
print(x)

[[0.05026084 0.91643899 0.53724217]
 [0.21307813 0.27108363 0.0955204 ]
 [0.42870474 0.0768663  0.22884047]
 [0.61821601 0.61868706 0.17247935]
 [0.75604754 0.2640704  0.18639503]]


In [9]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [11]:
# defining a list of different car companies or string elements.
arr_str=['mercedes','bmw']

In [14]:
# defining a list of number of cylinders in car of numberical element.
arr_num=[1,2,3,4,5]

In [23]:
np_arr_str=['mercedes','bmw']

In [24]:
np_arr_num=[1,2,3,4,5]

In [15]:
# printing the data type of lists.
print('data type of arr_str:',type(arr_str))
print('data type of arr_str:',type(arr_num))

data type of arr_str: <class 'list'>
data type of arr_str: <class 'list'>


In [25]:
# printing the data type after coversion  of lists to array.
print('data type of arr_str:',type(np_arr_str))
print('data type of arr_str:',type(np_arr_num))

data type of arr_str: <class 'list'>
data type of arr_str: <class 'list'>


In [31]:
arr2=np.arange(start=0,stop=10) 
print(arr2)
   # or
arr2=np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# adding a step  size of 5 to create an array.


In [5]:
matrix2=np.linspace(0,5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [6]:
matrix2=np.linspace(0,10)
matrix2

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
matrix2=np.linspace(10,10,10)
matrix2

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [9]:
matrix6=np.eye(6)
matrix6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [10]:
matrix6=np.eye(10)
matrix6

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
print('sine function',np.sin(4))
print('cos function',np.cos(4))
print('tan function',np.tan(4))

sine function -0.7568024953079282
cos function -0.6536436208636119
tan function 1.1578212823495777


In [15]:
np.exp(2)

np.float64(7.38905609893065)

In [16]:
arr5=np.array([2,3,6])
np.exp(arr5)

array([  7.3890561 ,  20.08553692, 403.42879349])

In [17]:
np.log(2)

np.float64(0.6931471805599453)

In [24]:
np.log10(10)

np.float64(1.0)

In [20]:
np.log(arr5)

array([0.69314718, 1.09861229, 1.79175947])

In [19]:
np.log10(8)

np.float64(0.9030899869919435)

In [25]:
l1=[1,2,3]
l2=[4,5,6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [29]:
arr7=np.arange(1,6)
print('arr7',arr7)
arr8=np.arange(3,8)
print('arr8',arr8)

arr7 [1 2 3 4 5]
arr8 [3 4 5 6 7]


In [54]:
print('Addition',arr7+arr8)
print('subtraction',arr8-arr7)
print('multiplaction',arr7*arr8)
print('divison',arr7/arr8)
print('inverse',1/arr7)
print('powers',arr7**arr8)

Addition [ 4  6  8 10 12]
subtraction [2 2 2 2 2]
multiplaction [ 3  8 15 24 35]
divison [0.33333333 0.5        0.6        0.66666667 0.71428571]
inverse [1.         0.5        0.33333333 0.25       0.2       ]
powers [    1    16   243  4096 78125]


In [37]:
matrix7=np.arange(1,10).reshape(3,3)
print(matrix7)
matrix8=np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
print('Addition',matrix7+matrix8)
print('subtraction',matrix8-matrix7)
print('multiplaction',matrix7*matrix8)
print('divison',matrix7/matrix8)

Addition [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
subtraction [[ 0. -2. -3.]
 [-4. -4. -6.]
 [-7. -8. -8.]]
multiplaction [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
divison [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\madhurima singh\AppData\Local\Temp\ipykernel_1076\1210551691.py:4: RuntimeWarning: divide by zero encountered in divide
  print('divison',matrix7/matrix8)


In [40]:
matrix9=np.arange(1,10).reshape(3,3)
print('first matrix:\n',matrix9)

first matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
matrix10=np.arange(11,20).reshape(3,3)
print('second matrix:\n',matrix10)
print(' ')

second matrix:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
 


In [42]:
print('multiplication:\n',matrix9*matrix10)

multiplication:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [57]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
rand_mat3=np.random.randn(3,3)
print(rand_mat3)

[[ 0.21143728 -1.44820964  0.60382531]
 [-0.06068911  0.2953807  -0.54466527]
 [-0.31807117  2.93078691  0.19160859]]


In [61]:
rand_matrix=np.random.randn(1,2,4)
print(rand_matrix)

[[[-0.45088779  0.53260282  0.16207637  0.62291392]
  [ 1.10197121  0.56103222  1.2051594   2.18462073]]]
